// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using TesteUEXAPI.Models;

namespace TesteUEXAPI.Data;

public partial class teste_uexContext : DbContext
{
    public teste_uexContext()
    {
    }

    public teste_uexContext(DbContextOptions<teste_uexContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Cidades> Cidades { get; set; }

    public virtual DbSet<Estados> Estados { get; set; }

    public virtual DbSet<Usuarios> Usuarios { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-7HFHGOF\\SQLEXPRESS;Initial Catalog=teste_uex;Persist Security Info=True;User ID=TesteUEXAdmin;Password=abc123...;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Cidades>(entity =>
        {
            entity.HasKey(e => e.id_cidade).HasName("PK__Cidades__8D4A7FD4F7FED08B");

            entity.Property(e => e.nome)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.id_estadoNavigation).WithMany(p => p.Cidades)
                .HasForeignKey(d => d.id_estado)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Cidades_Estados");
        });

        modelBuilder.Entity<Estados>(entity =>
        {
            entity.HasKey(e => e.id_estado).HasName("PK__Estados__86989FB2124E3131");

            entity.Property(e => e.codigo_ibge)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.nome)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.sigla)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Usuarios>(entity =>
        {
            entity.HasKey(e => e.id_usuario).HasName("PK__Usuarios__4E3E04ADB58BBE5A");

            entity.Property(e => e.Bairro)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.CPF)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Cep)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Cidade)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Estado)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Latitude)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Longitude)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Numero)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Rua)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Telefone)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.nome)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.senha)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}