// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TesteUEXAPI.Models;

public partial class Cidades
{
    public int id_cidade { get; set; }

    public string nome { get; set; }

    public int id_estado { get; set; }

    public virtual Estados id_estadoNavigation { get; set; }
}