// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TesteUEXAPI.Models;

public partial class Estados
{
    public int id_estado { get; set; }

    public string nome { get; set; }

    public string sigla { get; set; }

    public string codigo_ibge { get; set; }

    public virtual ICollection<Cidades> Cidades { get; set; } = new List<Cidades>();
}