// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TesteUEXAPI.Models;

public partial class Usuarios
{
    public int id_usuario { get; set; }

    public string nome { get; set; }

    public string CPF { get; set; }

    public string Cep { get; set; }

    public string Rua { get; set; }

    public string Numero { get; set; }

    public string Bairro { get; set; }

    public string Cidade { get; set; }

    public string Estado { get; set; }

    public string Telefone { get; set; }

    public string Latitude { get; set; }

    public string Longitude { get; set; }

    public string senha { get; set; }
}